# Assignment 5

Note: It is mandatory to use methods from pandas library to solve the following questions

1. Create a series using any numpy array. Print it's data type.
2. Create a dataframe using Python dictionary with any sample data.
3. Create 4 separate series and combine them into 1 dataframe.
4. Read car-sales.csv.
               - print it's columns.
               - Print first 100 rows of csv.
               - Print data for only 3 columns.
               - Print all distinct values from Make column.
               - Print count of cars for each color.
               - Remove $ symbol from Price column.
               - Print max price, min price, sum of prices, Mean and median.
               - Print first 3 rows and values for only first 3 columns. Use loc function.
               - Add new column id and assign unique ids to each row and store result into new csv. Push the new file into local mysql db.
               - Print count of cars with number of doors = 4.
               - Print all rows where price is between 10000 and 20000.
               - Store data for different "Make" entries in different csv. Name of the csv files generated should be <Make_value>.csv. Eg. All rows with Make = Toyota should go into Toyota.csv.

The code should be generic. ie If someone adds a new entry in Make column, it should still work.

Eg. If someone adds a new row with Make = “Kia“, then new csv should be generated with kia.csv name.

5. Read data.csv.

               - Split the given csv and create multiple separate csvs with n rows in each of the csvs. Value of n should be taken from the user. Name of each file should be data_1.csv, data_2.csv and so on.

In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [2]:
arr = np.array([10, 20, 30, 40, 50])
series = pd.Series(arr)
print(series)
print("Data Type:", series.dtype)

0    10
1    20
2    30
3    40
4    50
dtype: int64
Data Type: int64

In [3]:
data = {
    "Name": ["Person1", "Person2", "Person3"],
    "Age": [21, 22, 23],
    "City": ["Pune", "Mumbai", "Delhi"]
}

df = pd.DataFrame(data)

print(df)

      Name  Age    City
0  Person1   21    Pune
1  Person2   22  Mumbai
2  Person3   23   Delhi

In [4]:
s1 = pd.Series([1, 2, 3])
s2 = pd.Series(["A", "B", "C"])
s3 = pd.Series([100, 200, 300])
s4 = pd.Series(["Pune", "Mumbai", "Delhi"])

df = pd.DataFrame({
    "ID": s1,
    "Grade": s2,
    "Marks": s3,
    "City": s4
})

print(df)

   ID Grade  Marks    City
0   1     A    100    Pune
1   2     B    200  Mumbai
2   3     C    300   Delhi

In [5]:
cars = pd.read_csv("car_sales.csv")
print(cars.head())

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [6]:
print(cars.columns)

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='str')

In [8]:
cars.head(100)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [10]:
cars[["Make", "Colour", "Price"]]

     Make Colour       Price
0  Toyota  White   $4,000.00
1   Honda    Red   $5,000.00
2  Toyota   Blue   $7,000.00
3     BMW  Black  $22,000.00
4  Nissan  White   $3,500.00
5  Toyota  Green   $4,500.00
6   Honda   Blue   $7,500.00
7   Honda   Blue   $7,000.00
8  Toyota  White   $6,250.00
9  Nissan  White   $9,700.00

In [11]:
cars["Make"].unique()

<StringArray>
['Toyota', 'Honda', 'BMW', 'Nissan']
Length: 4, dtype: str

In [12]:
cars["Colour"].value_counts()

Colour
White    4
Blue     3
Red      1
Black    1
Green    1
Name: count, dtype: int64

In [14]:
cars["Price"] = cars["Price"].replace('[\$,]', '', regex=True)
cars["Price"] = cars["Price"].astype(float)
print(cars["Price"])

0     4000.0
1     5000.0
2     7000.0
3    22000.0
4     3500.0
5     4500.0
6     7500.0
7     7000.0
8     6250.0
9     9700.0
Name: Price, dtype: float64

In [15]:
print("Max Price:", cars["Price"].max())

print("Min Price:", cars["Price"].min())

print("Sum:", cars["Price"].sum())

print("Mean:", cars["Price"].mean())

print("Median:", cars["Price"].median())

Max Price: 22000.0
Min Price: 3500.0
Sum: 76450.0
Mean: 7645.0
Median: 6625.0

In [16]:
cars.loc[0:2, ["Make", "Colour", "Price"]]

     Make Colour   Price
0  Toyota  White  4000.0
1   Honda    Red  5000.0
2  Toyota   Blue  7000.0

In [18]:
cars["id"] = range(1, len(cars) + 1)

cars.head()

     Make Colour  Odometer (KM)  Doors    Price  id
0  Toyota  White         150043      4   4000.0   1
1   Honda    Red          87899      4   5000.0   2
2  Toyota   Blue          32549      3   7000.0   3
3     BMW  Black          11179      5  22000.0   4
4  Nissan  White         213095      4   3500.0   5

In [19]:
cars.to_csv("car-sales-new.csv", index=False)

In [20]:
engine = create_engine(
    "mysql+pymysql://root:root@localhost/car_db"
)

cars.to_sql(
    name="car_sales",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data inserted into MySQL")

Data inserted into MySQL

In [21]:
cars[cars["Doors"] == 4].shape[0]

8

In [22]:
filtered = cars[
    (cars["Price"] >= 10000) &
    (cars["Price"] <= 20000)
]

print(filtered)

Empty DataFrame
Columns: [Make, Colour, Odometer (KM), Doors, Price, id]
Index: []

In [23]:
makes = cars["Make"].unique()

for make in makes:
    make_df = cars[cars["Make"] == make]
    filename = f"{make}.csv"
    make_df.to_csv(filename, index=False)
    print(filename, "created")

Toyota.csv created
Honda.csv created
BMW.csv created
Nissan.csv created

In [24]:
data = pd.read_csv("data.csv")

data.head()

       Date  Clicks  Visits
0  1/1/2020   369.0   781.0
1  1/2/2020   213.0   577.0
2  1/3/2020   405.0   733.0
3  1/4/2020   161.0   683.0
4  1/5/2020   140.0   967.0

In [28]:
n = int(input("Enter number of rows per file: "))

In [29]:
rows = len(data)

file_number = 1

for start in range(0, rows, n):
    end = start + n
    split_data = data.iloc[start:end]
    filename = f"data_{file_number}.csv"
    split_data.to_csv(filename, index=False)
    print(filename, "created")
    file_number += 1

data_1.csv created
data_2.csv created
data_3.csv created
data_4.csv created